# This file contains values from Cookiecutter

default_context:
  project_name: "dynnode2vec"
  project_description: "dynnode2vec is a package to embed dynamic graphs"
  organization: "pedugnat"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "pedugnat"
  email: " "
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
